# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --progress=plain -t luantruong/cicd
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push luantruong/cicd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${ { secrets.EC2_SSH_KEY }}
          host: ${ { secrets.HOST_DNS }}
          username: ${ { secrets.USERNAME }}

          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull luantruong/cicd:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 5272:5272 --restart unless-stopped luantruong/cicd:latest
