name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: List files for debugging
        run: ls -al ${{ github.workspace }}
      - name: Build the Docker image
        run: docker build --progress=plain -t luantruong123/cicd ${{ github.workspace }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push the Docker image
        run: docker push luantruong123/cicd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull luantruong123/cicd:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 5272:5272 --restart unless-stopped luantruong123/cicd:latest
